### ISSUE TITLE
Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by ishansan38** [domantasm96/URL-categorization-using-machine-learning#1]
Getting this error even after running 500 / 1000 steps, but unable to get any urls parsed.
![screenshot](https://user-images.githubusercontent.com/21282864/41848482-334db472-789b-11e8-9e27-c351695c7517.png)

Could you please explain why I am encountering this error?

Thanks in advance.

**Comment by domantasm96** [comment]
Hey! 
Thanks for pointing out the problems with this project. To be honest this was my 1 - month university project it is no suprise that some problem may occur.
One of the mistakes that I made in this project is that I didn't seperate testing and training data sets so the final prediction result is not accurate.
I will try to update this repository with the solution to your problem in a few weeks.
Have a good day!

**Comment by domantasm96** [comment]
I hope you are not dealing with the certain problem at the moment because code was refactored and new features have been added. 

If something wrong with execution or there are any other issues, please reopen/create a issue.
