### ISSUE TITLE
Additional Model Training

### ISSUE THREAD

**Issue by Reeceline** [domantasm96/URL-categorization-using-machine-learning#7]
Thank you so much for this! Any suggestions on how one would improve the current model? I do see the dataset is quite outdated. I'd like to train it further and add more categories. 

I do have a list of millions of websites and their basic category that I assume this could use to scan for categorization keywords. 

Thanks!

Warm Regards,
Reece

**Comment by domantasm96** [comment]
Hey @Reeceline !

There are some ideas how to improve the current model: https://github.com/domantasm96/URL-categorization-using-machine-learning/issues/6#issuecomment-782650885
